create database  evaluacion_hito3_2022;
use evaluacion_hito3_2022;

# SEGUNDA PREGUNTA COMPARA 2 CADENAS
CREATE OR REPLACE FUNCTION COMPARAR_CADENA(A VARCHAR(20), B VARCHAR(20))
RETURNS VARCHAR(40)
BEGIN
    DECLARE RESPUESTA VARCHAR(40) DEFAULT '';
    IF STRCMP(A,B)=0 THEN SET RESPUESTA='SON IGUALES';
        ELSE  SET RESPUESTA='SON DIFFERENTES';
        END IF;
    RETURN RESPUESTA;
end;

SELECT COMPARAR_CADENA('MARIO','MARIO');

#                       TERCERA PERGUNTA MANEJO DE SERIES
#ACREAR LA TABLA
CREATE TABLE CLIENTES(
    ID_CLIENT INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY ,
    FULLNAME VARCHAR(20),
    LASTNAME VARCHAR(20),
    AGE INT,
    GENERO CHAR(1)
);
INSERT INTO CLIENTES (FULLNAME,LASTNAME,AGE,GENERO)
VALUES('PEDRO','MENDOZA GUTIERREZ',22,'V'),
      ('LORENA','MIRANDA SALAZAR',19,'M'),
      ('RODRIGO','LENIN MENDOAZA',24,'V');

CREATE OR REPLACE FUNCTION EDAD_MAXIMA()
RETURNS INTEGER
BEGIN
    DECLARE EDADMAX INTEGER DEFAULT 0;
    SELECT MAX(CLIENTES.AGE) INTO EDADMAX
    FROM CLIENTES;
    RETURN EDADMAX;
end;
SELECT EDAD_MAXIMA();


CREATE OR REPLACE FUNCTION ACENDENTE_DECENDENTE()
RETURNS TEXT
BEGIN
    DECLARE RESPUESTA TEXT DEFAULT '';
    DECLARE NUMEROAUX INTEGER DEFAULT 0;

    IF EDAD_MAXIMA()%2=0 THEN
        WHILE NUMEROAUX<=EDAD_MAXIMA() DO
            SET RESPUESTA=CONCAT(RESPUESTA,NUMEROAUX,',');
            SET NUMEROAUX=NUMEROAUX+2;
        end while;
    ELSE
        SET NUMEROAUX=EDAD_MAXIMA();
        WHILE NUMEROAUX>=0 DO
            SET RESPUESTA=CONCAT(RESPUESTA,NUMEROAUX,',');
            SET NUMEROAUX=NUMEROAUX-2;
        end while;
    end if;
    RETURN RESPUESTA;
END;

SELECT ACENDENTE_DECENDENTE();

INSERT INTO CLIENTES (FULLNAME,LASTNAME,AGE,GENERO)
VALUES('LORENZO','MENDOZA GUTIERREZ',25,'V');

#PREGUNTA 4       SERIE DE FIBONANCI

CREATE OR REPLACE FUNCTION  SERIE_DE_FIBONANCI(TOPE INTEGER)
RETURNS TEXT
BEGIN
    DECLARE A INTEGER DEFAULT 0;
    DECLARE B INTEGER DEFAULT 1;
    DECLARE AUXILIAR INTEGER DEFAULT 0;
    DECLARE CADENA TEXT DEFAULT '';
    SET CADENA=CONCAT(A,',',B,',');

IF TOPE=1 THEN SET CADENA='0';
ELSEIF TOPE=2 THEN SET CADENA='0,1';
ELSEIF TOPE<=0 THEN SET CADENA='DEBE SER MAYOR A CERO';
ELSE
    REPEAT
    SET AUXILIAR=A+B;
    SET CADENA=CONCAT(CADENA,AUXILIAR,',');
    SET A=B;
    SET B=AUXILIAR;
    until AUXILIAR>=TOPE-2 end repeat;
END IF;
    RETURN CADENA;
END;

SELECT SERIE_DE_FIBONANCI(7);

#CREAR UNA FUNCION QUE RECIBA UN PARAMETRO DEL TIPO TEXT
#LA FUNCION RETIORNA LA CADENA AL REVES

CREATE OR REPLACE FUNCTION  VOLTEAR_CADENA(PALABRA TEXT)
RETURNS TEXT
BEGIN
    DECLARE RESPUESTA TEXT DEFAULT '';
    SET RESPUESTA= REVERSE(PALABRA);
    RETURN PALABRA;
end;
SELECT VOLTEAR_CADENA('HOLA');