
#////////////////////////////////////////////////////////////////////////
#///////////////         PREGUNTA 9  /////////////////////////////////
#/////////////////////////////////////////////////////////////////


CREATE DATABASE PRACTICA_H4;
USE PRACTICA_H4;

CREATE TABLE  DEPARTAMENTO
(
    ID_DEP INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50)
);

CREATE TABLE PROVINCIA
(
    ID_PROV INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    ID_DEP INT NOT NULL,
    FOREIGN KEY (ID_DEP) REFERENCES DEPARTAMENTO(ID_DEP)
);

CREATE TABLE PROYECTO
(
    ID_PROY INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_PROY VARCHAR(100),
    TIPO_PROY VARCHAR(30)
);

CREATE TABLE PERSONA
(
  ID_PER INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  NOMBRE VARCHAR(20),
  APELLIDOS VARCHAR(50),
  FECHA_NAC DATE,
  EDAD INT,
  EMAIL VARCHAR(50),
  ID_DEP INT NOT NULL ,
  ID_PROV INT NOT NULL,
  GENERO VARCHAR(1),
  FOREIGN KEY (ID_PROV) REFERENCES  PROVINCIA(ID_PROV),
  FOREIGN KEY (ID_DEP) REFERENCES DEPARTAMENTO(ID_DEP)
);
CREATE TABLE DETALLE_PROYECTO
(
    ID_DP INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_PER INT NOT NULL ,
    ID_PROY INT NOT NULL ,

    FOREIGN KEY (ID_PROY) REFERENCES PROYECTO(ID_PROY),
    FOREIGN KEY (ID_PER) REFERENCES PERSONA(ID_PER)
);



INSERT INTO  DEPARTAMENTO(NOMBRE)
VALUES ('LA PAZ'),
       ('SANTA CRUZ'),
       ('BENI'),
       ('ORURO'),
       ('CHUQUISACA'),
       ('TARIJA'),
       ('PANDO'),
       ('POTOSI'),
       ('COCHABAMBA');


INSERT INTO  PROVINCIA(NOMBRE, ID_DEP)
VALUES ('VIACHA',1),
       ('ROBORE',2),
       ('MAGDALENA',3),
       ('CHALLAPATA',4),
       ('TARABUCO',5),
       ('VILLAMONTES',6),
       ('GUAYARAMERIN',7),
       ('UYUNI',8),
       ('AIQUILE',9);

INSERT INTO PERSONA (NOMBRE, APELLIDOS, FECHA_NAC, EDAD, EMAIL, ID_DEP, ID_PROV, GENERO)
VALUES ('RODRIGO','MENODZA UGARTE','1999-11-21',23,'RODRIGO@GMAIL.COM',1,1,'M'),
       ('MARIA','LAURA TORREZ','1999-12-16',25,'MARIA@GAMIL.COM',2,2,'F'),
       ('AUGUSTO','MEDRANO LOZA','1998-09-12',24,'AUGUSTO@GMAIL.COM',3,3,'M'),
       ('MARIANO','FERNANDEZ GUTIERREZ','1995-09-12',27,'MARIANO@GMAIL.COM',4,4,'M'),
       ('LORENA','ZAMUDIO LLANOS','2000-09-12',22,'LORENA@GMAIL.COM',5,5,'F');

INSERT INTO  PROYECTO(NOMBRE_PROY, TIPO_PROY)
VALUES('ANIMALES','BIOLOGIA'),
      ('PREHISTORIA','ANTROPOLOGIA'),
      ('MICROBIOS','BIOLOGIA'),
      ('REDES Y SISTEMAS','TECNOLOGIA'),
      ('FLUJO MAGNETICO','FISICA');
INSERT INTO DETALLE_PROYECTO(ID_PER, ID_PROY)
VALUES (1,2),
       (2,1),
       (3,4),
       (4,3);




#//////////////////////////////////////////////////////////////////////////////////
#////////////////        PREGUNTA 10       /////////////////////////////////////
#/////////////////////////////////////////////////////////////////////////////////////

CREATE OR REPLACE FUNCTION SERIE_FIBONANCI(NUMBER INTEGER)

RETURNS TEXT
BEGIN
    DECLARE A INTEGER DEFAULT 0;
    DECLARE B INTEGER DEFAULT 1;
    DECLARE AUX INTEGER DEFAULT 0;
    DECLARE CONTADOR INTEGER DEFAULT 0;
    DECLARE CADENA TEXT DEFAULT '';
    SET CADENA =CONCAT(A,',',B);

IF NUMBER=1 THEN SET CADENA='0';
ELSEIF NUMBER=2 THEN SET CADENA='0,1';
ELSEIF NUMBER<=0 THEN SET CADENA='EL NUMERO DEBE SER MAYOR A CERO';
ELSE
            REPEAT

            SET AUX=A+B;
            SET CADENA = CONCAT(CADENA,',',AUX);
            SET A=B;
            SET B=AUX;
            SET CONTADOR=CONTADOR+1;
            UNTIL CONTADOR = NUMBER-2 END REPEAT;

END IF;
    RETURN CADENA;
END;

CREATE OR REPLACE FUNCTION CONTAR_FIBONANCI(SERIE TEXT)
RETURNS INTEGER
BEGIN
    DECLARE SUMA INTEGER DEFAULT 0;
    DECLARE CONT INTEGER DEFAULT 1;
    DECLARE FINAL INTEGER DEFAULT CHAR_LENGTH(SERIE);

  REPEAT
   SET SUMA =SUMA + SUBSTRING(SERIE,CONT,1);
   SET CONT=CONT+2;
  until  CONT> FINAL END REPEAT;

    RETURN SUMA;
end;

SELECT SERIE_FIBONANCI(5);
SELECT CONTAR_FIBONANCI(SERIE_FIBONANCI(5));


#//////////////////////////////////////////////////////////////////////////////////
#////////////////        PREGUNTA 11       /////////////////////////////////////
#/////////////////////////////////////////////////////////////////////////////////////

INSERT INTO DEPARTAMENTO(NOMBRE)
VALUES('EL ALTO');

INSERT INTO PERSONA (NOMBRE, APELLIDOS, FECHA_NAC, EDAD, EMAIL, ID_DEP, ID_PROV, GENERO)
VALUES ('CARMEN','CALLE UGARTE','2000-10-10',23,'CARMEN@GMAIL.COM',10,1,'F'),
       ('GABRIELA','BARRA MENDOZA','2000-10-10',23,'GABRIELA@GMAIL.COM',10,1,'F');
INSERT INTO DETALLE_PROYECTO(ID_PER, ID_PROY)
VALUES (6,4),
       (7,5);


CREATE OR REPLACE VIEW BUSQUEDA AS
SELECT CONCAT(PERSONA.NOMBRE,' ',PERSONA.APELLIDOS) AS NOMBRES_Y_APELLIDOS,
           PERSONA.EDAD AS EDAD,
           PERSONA.FECHA_NAC AS FECHA_DE_NACIMIENTO,
        PROYECTO.NOMBRE_PROY AS NOMBRE_DEL_PROYECTO
FROM PERSONA
INNER JOIN DEPARTAMENTO ON PERSONA.ID_DEP = DEPARTAMENTO.ID_DEP
INNER JOIN DETALLE_PROYECTO ON PERSONA.ID_PER = DETALLE_PROYECTO.ID_PER
INNER JOIN PROYECTO ON DETALLE_PROYECTO.ID_PROY = PROYECTO.ID_PROY

WHERE PERSONA.GENERO='F' AND  DEPARTAMENTO.NOMBRE='EL ALTO' AND PERSONA.FECHA_NAC='2000-10-10' ;

SELECT * FROM BUSQUEDA;

#//////////////////////////////////////////////////////////////////////////////////
#////////////////        PREGUNTA 12       /////////////////////////////////////
#/////////////////////////////////////////////////////////////////////////////////////


ALTER TABLE PROYECTO ADD (ESTADO VARCHAR(30));

INSERT INTO PROYECTO(NOMBRE_PROY, TIPO_PROY)
VALUES ('EDUCACION PERSONAS ESPECIALES','EDUCACION'),
       ('PLANTACION DE ARBOLES','FORESTACION'),
       ('LOS AZTECAS','CULTURA');

CREATE OR REPLACE TRIGGER UPDATE_TIP_PROYCT
BEFORE UPDATE ON PROYECTO
FOR EACH ROW
    BEGIN
        IF  NEW.TIPO_PROY='EDUCACION'OR  NEW.TIPO_PROY ='FORESTACION' OR  NEW.TIPO_PROY= 'CULTURA'
            THEN SET NEW.ESTADO='ACTIVO';
        ELSE
            SET NEW.ESTADO='INACTIVO';
        END IF;
    END;

CREATE OR REPLACE TRIGGER ADD_TIP_PROYCT
BEFORE  INSERT ON PROYECTO
FOR EACH ROW
    BEGIN
        IF  NEW.TIPO_PROY='EDUCACION'OR  NEW.TIPO_PROY ='FORESTACION' OR  NEW.TIPO_PROY= 'CULTURA'
            THEN SET NEW.ESTADO='ACTIVO';
        ELSE
            SET NEW.ESTADO='INACTIVO';
        END IF;
    end;

INSERT INTO PROYECTO(NOMBRE_PROY, TIPO_PROY)
VALUES ('ARBOLESS','EDUCACION');
SELECT

#//////////////////////////////////////////////////////////////////////////////////
#////////////////        PREGUNTA 13       /////////////////////////////////////
#/////////////////////////////////////////////////////////////////////////////////////

CREATE OR REPLACE TRIGGER AGREGAR_EDAD
BEFORE INSERT ON PERSONA
FOR EACH ROW
    BEGIN
        SET NEW.EDAD= TIMESTAMPDIFF(YEAR,NEW.FECHA_NAC,CURDATE());
    end;

INSERT INTO  PERSONA(NOMBRE, APELLIDOS, FECHA_NAC, EMAIL, ID_DEP, ID_PROV, GENERO)
VALUES  ('MARIA','GALARSA ORTEGA','1992-12-15','MARIA@GMAIL.COM',3,3,'F');

SELECT *FROM PERSONA;
#//////////////////////////////////////////////////////////////////////////////////
#////////////////        PREGUNTA 14     /////////////////////////////////////
#/////////////////////////////////////////////////////////////////////////////////////

CREATE TABLE COPIA_PERSONA
(
  NOMBRE VARCHAR(20),
  APELLIDOS VARCHAR(50),
  FECHA_NAC DATE,
  EDAD INT,
  EMAIL VARCHAR(50),
  ID_DEP INT NOT NULL ,
  ID_PROV INT NOT NULL,
  GENERO VARCHAR(1),
  FOREIGN KEY (ID_PROV) REFERENCES  PROVINCIA(ID_PROV),
  FOREIGN KEY (ID_DEP) REFERENCES DEPARTAMENTO(ID_DEP)
);

CREATE OR REPLACE TRIGGER COPIAR_PERSONA
BEFORE INSERT ON PERSONA
FOR EACH ROW
    BEGIN
        INSERT INTO COPIA_PERSONA(NOMBRE, APELLIDOS, FECHA_NAC, EDAD, EMAIL, ID_DEP, ID_PROV, GENERO)
        VALUES(NEW.NOMBRE,NEW.APELLIDOS,NEW.FECHA_NAC,NEW.EDAD,NEW.EMAIL,NEW.ID_DEP,NEW.ID_PROV,NEW.GENERO);
    end;

INSERT INTO PERSONA(NOMBRE, APELLIDOS, FECHA_NAC, EDAD, EMAIL, ID_DEP, ID_PROV, GENERO)
VALUES ('PDRO','ALIAGA ORTEGA','2000-12-15',22,'ALEJANDRA@GMAIL.COM',5,5,'M');

SELECT*FROM COPIA_PERSONA;
#//////////////////////////////////////////////////////////////////////////////////
#////////////////        PREGUNTA 15     /////////////////////////////////////
#/////////////////////////////////////////////////////////////////////////////////////

CREATE OR REPLACE VIEW TODAS_LAS_TABLAS AS
SELECT
    CONCAT(PERSONA.NOMBRE,PERSONA.APELLIDOS) AS NOMBRE_Y_APELLIDOS,
    PERSONA.EDAD AS EDAD,
    DEPARTAMENTO.NOMBRE AS DEPARTAMENTO,
    PROVINCIA.NOMBRE AS PROVINCIA,
    CONCAT(PROYECTO.NOMBRE_PROY,': ',TIPO_PROY) AS PROYECTO

FROM PERSONA
INNER JOIN DEPARTAMENTO ON PERSONA.ID_DEP = DEPARTAMENTO.ID_DEP
INNER JOIN PROVINCIA ON PERSONA.ID_PROV = PROVINCIA.ID_PROV
INNER JOIN DETALLE_PROYECTO ON PERSONA.ID_PER = DETALLE_PROYECTO.ID_PER
INNER JOIN PROYECTO ON DETALLE_PROYECTO.ID_PROY = PROYECTO.ID_PROY;

SELECT * FROM (TODAS_LAS_TABLAS);