CREATE DATABASE DEFESA_HITO4;
USE DEFESA_HITO4;

CREATE TABLE  DEPARTAMENTO
(
    ID_DEP INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50)
);

CREATE TABLE PROVINCIA
(
    ID_PROV INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    ID_DEP INT NOT NULL,
    FOREIGN KEY (ID_DEP) REFERENCES DEPARTAMENTO(ID_DEP)
);

CREATE TABLE PROYECTO
(
    ID_PROY INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_PROY VARCHAR(100),
    TIPO_PROY VARCHAR(30)
);

CREATE TABLE DETALLE_PROYECTO
(
    ID_DP INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_PER INT NOT NULL ,
    ID_PROY INT NOT NULL ,

    FOREIGN KEY (ID_PROY) REFERENCES PROYECTO(ID_PROY),
    FOREIGN KEY (ID_PER) REFERENCES PERSONA(ID_PER)
);

CREATE TABLE PERSONA
(
  ID_PER INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  NOMBRE VARCHAR(20),
  APELLIDOS VARCHAR(50),
  FECHA_NAC DATE,
  EDAD INT,
  EMAIL VARCHAR(50),
  ID_DEP INT NOT NULL ,
  ID_PROV INT NOT NULL,
  GENERO VARCHAR(1),
  FOREIGN KEY (ID_PROV) REFERENCES  PROVINCIA(ID_PROV)
  FOREIGN KEY (ID_DEP) REFERENCES DEPARTAMENTO(ID_DEP),

);

#///////////////////////////////////////////////////////////////////////////////////////////
#//////////////////            PREGUNTA         ////////////////////////////////////////////
#///////////////////////////////////////////////////////////////////////////////////////////

INSERT INTO  DEPARTAMENTO(NOMBRE)
VALUES ('LA PAZ'),
       ('SANTA CRUZ'),
       ('BENI'),
       ('ORURO'),
       ('CHUQUISACA');

INSERT INTO  PROVINCIA(NOMBRE, ID_DEP)
VALUES ('VIACHA','1'),
       ('ROBORE','2'),
       ('MAGDALENA','3'),
       ('CHALLAPATA','4'),
       ('TARABUCO','5');

INSERT INTO PERSONA (NOMBRE, APELLIDOS, FECHA_NAC, EDAD, EMAIL, ID_DEP, ID_PROV, GENERO)
VALUES ('RODRIGO','MENODZA UGARTE','1999-11-21',23,'RODRIGO@GMAIL.COM',1,1,'M'),
       ('MARIA','LAURA TORREZ','1999-12-16',25,'MARIA@GAMIL.COM',2,2,'F');

INSERT INTO DETALLE_PROYECTO(ID_PER, ID_PROY)
VALUES (1,2),
       (2,1);

INSERT INTO  PROYECTO(NOMBRE_PROY, TIPO_PROY)
VALUES('ANIMALES','BIOLOGIA'),
      ('PREHISTORIA','ANTROPOLOGIA');

CREATE TABLE AUDIT_PROYECT
(
    ID_AUDIT_PROY INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NOMBRE_PROY_ANTERIOR VARCHAR(30),
    NOMBRE_PROY_POSTERIOR VARCHAR(30),
    TIPO_PROY_ANTERIOR VARCHAR(30),
    TIPÓ_PROY_POSTERIOS VARCHAR(30),
    OPERATION VARCHAR(30),
    USER_ID_ VARCHAR(30),
    HOSTANAME VARCHAR(30)
);

CREATE OR REPLACE TRIGGER AUDIT_PROYECTOS
    BEFORE UPDATE ON PROYECTO
    FOR EACH ROW

    BEGIN
        DECLARE NOM_POSTERIOS VARCHAR(30) DEFAULT NEW.NOMBRE_PROY;
        DECLARE NOM_ANTERIOR VARCHAR(30) DEFAULT OLD.NOMBRE_PROY;
        DECLARE TIP_ANT VARCHAR(30) DEFAULT OLD.TIPO_PROY;
        DECLARE TIP_POST VARCHAR(30) DEFAULT  NEW.TIPO_PROY;
        DECLARE OP VARCHAR(30) DEFAULT 'UPDATE';

        INSERT INTO AUDIT_PROYECT
        ( NOMBRE_PROY_ANTERIOR, NOMBRE_PROY_POSTERIOR, TIPO_PROY_ANTERIOR, TIPÓ_PROY_POSTERIOS, OPERATION, USER_ID_, HOSTANAME)
         VALUES (NOM_ANTERIOR,NOM_POSTERIOS,TIP_ANT,TIP_POST,OP,USER(),@@HOSTNAME);

    end;
SELECT * FROM AUDIT_PROYECT;

#///////////////////////////////////////////////////////////////////
#///////////////         PREGUNTA 2          ///////////////////////
#///////////////////////////////////////////////////////////////////

CREATE OR REPLACE VIEW  REPORTE_PROYECTOS AS
SELECT CONCAT(PERSONA.NOMBRE,' ',PERSONA.APELLIDOS) AS FULLNAME,
       CONCAT(PROYECTO.NOMBRE_PROY,': ',PROYECTO.TIPO_PROY) AS DESC_PROYECTO,
       DEPARTAMENTO.NOMBRE AS DEPARTAMENTO,
       (
           CASE
               WHEN DEPARTAMENTO.NOMBRE='LA PAZ' THEN 'LPZ'
               WHEN DEPARTAMENTO.NOMBRE ='SANTA CRUZ' THEN 'SCZ'
               WHEN DEPARTAMENTO.NOMBRE= 'BENI' THEN 'BEN'
               WHEN DEPARTAMENTO.NOMBRE ='CHUQUISACA' THEN 'CHQSCA'
               WHEN DEPARTAMENTO.NOMBRE ='ORURO' THEN 'OR'
            END
           ) AS CODIGO_DEP
FROM PERSONA
INNER JOIN DEPARTAMENTO ON PERSONA.ID_DEP = DEPARTAMENTO.ID_DEP
INNER JOIN DETALLE_PROYECTO ON PERSONA.ID_PER = DETALLE_PROYECTO.ID_PER
INNER JOIN PROYECTO ON DETALLE_PROYECTO.ID_PROY = PROYECTO.ID_PROY;

SELECT * FROM REPORTE_PROYECTOS;

#///////////////////////////////////////////////////////////////////////////
#/////////////////          PREGUNTA 3   ///////////////////////////////////
#///////////////////////////////////////////////////////////////////////////

